# Generated by Django 5.1.4 on 2025-04-23 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("camera_device", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="positionpreset",
            name="sort_index",
            field=models.IntegerField(default=0),
        ),
    ]
