# Generated by Django 5.1.4 on 2025-04-23 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera_device', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='positionpreset',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
