# Generated by Django 5.1.4 on 2025-04-23 06:45

from django.db import migrations, models
from django.db.models import F, Window
from django.db.models.functions import RowNumber


class Migration(migrations.Migration):

    dependencies = [
        ("camera_device", "0002_positionpreset_is_default"),
    ]

    def backfill_sort_index(apps, schema_editor):
        PositionPreset = apps.get_model("camera_device", "PositionPreset")

        qs = PositionPreset.objects.filter(deleted=False).annotate(
            rn=Window(
                expression=RowNumber(),
                partition_by=[F("location_id")],
                order_by=F("id").asc(),
            )
        )

        to_update = []
        for obj in qs:
            obj.sort_index = obj.rn
            to_update.append(obj)
        PositionPreset.objects.bulk_update(to_update, ["sort_index"], batch_size=500)

    operations = [
        migrations.AddField(
            model_name="positionpreset",
            name="sort_index",
            field=models.IntegerField(default=0),
        ),
        migrations.RunPython(backfill_sort_index, migrations.RunPython.noop),
    ]
