# Generated by Django 5.1.4 on 2025-03-21 13:02
from django.db import migrations

MIGRATION_ID = 1584456952002


class Migration(migrations.Migration):

    dependencies = [
        ("facility", "0490_migrate_assets"),
    ]

    operations = []
