# Generated by Django 5.1.4 on 2025-03-21 13:02
from django.core.paginator import Paginator
from django.db import migrations

MIGRATION_ID = 1584456952002


def migrate_vitals_observation_device_config(apps, schema_editor):
    from care.emr.models import Device
    from care.facility.utils import disable_auto_time

    enable_auto_time = disable_auto_time(Device)

    Device.objects.filter(metadata__class__in=("HL7MONITOR", "VENTILATOR")).update(
        care_type="vitals-observation"
    )

    sub_type_map = {
        "HL7MONITOR": "HL7-Monitor",
        "VENTILATOR": "Ventilator",
    }

    queryset = Device.objects.filter(care_type="vitals-observation").order_by("id")
    paginator = Paginator(queryset, 1000)
    for page in paginator.page_range:
        bulk = []
        for device in paginator.page(page):
            metadata = device.metadata
            # TODO: switch to read from meta once @sainak is done with the changes
            metadata["type"] = sub_type_map[metadata.pop("class")]
            connection_meta = metadata.pop("connection_meta", {})
            metadata["endpoint_address"] = connection_meta.get("local_ip_address")
            bulk.append(device)
        Device.objects.bulk_update(bulk, ["metadata"])

    enable_auto_time()


def reverse_migrate_vitals_observation_device_config(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("facility", "0490_migrate_assets"),
    ]

    operations = [
        migrations.RunPython(
            migrate_vitals_observation_device_config,
            reverse_migrate_vitals_observation_device_config,
        ),
    ]
